### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kentcdodds** [mikenikles/jscodeshift-ava-to-jest#1]
I really like how https://github.com/avajs/ava-codemods works :)

**Comment by mikenikles** [comment]
Thanks @kentcdodds, that looks awesome. I'll try to apply it. I will also have a chance later today to apply my ava-to-jest jscodeshift on two production builds, which will give me a good idea of what's currently missing here.

**Comment by kentcdodds** [comment]
I tried running this codemod on my own project and I ended up having to git clone the repo and run the build to get it working. But even some of the supported features didn't quite work and I had several files where there were errors and it failed to change anything. This was about a week ago, so I can't remember exactly what the issues were (sorry about that). Have you had any success running this in other projects? Is there a better way to use this codemod?

Thanks again for your work on it!

**Comment by mikenikles** [comment]
Hey @kentcdodds, I have a local version that is similar to what you suggested above. It exposes a script that takes a test file pattern and does all the magic behind the scenes.

I'm on the road, but let me try and make this a priority asap. I appreciate you took the time to use it. I have three projects now waiting to get converted to Jest, so I'll have first-hand experience shortly.
